### ISSUE TITLE
problem with oauth credentials

### ISSUE THREAD

**Issue by MonneOnrust** [postmanlabs/postman-runtime#137]
I’m trying to get an OAuth2.0 access token for my web request, but I keep getting an error. 

The authorization server is an Azure Active Directory instance. There an application is set up as a web app with client credentials and the getpostman.com reply URL. 

I’ve tried different authURLs, but all with the same response. When I click Request Token, the error _‘Error getting access token from client_credentials’ flow. Could not send request’_ occurs. When I look in the development tools, I see a 400 Bad Request in the response with the following body:
_{"error":"invalid_request","error_description":"AADSTS90014: 'client_assertion' or 'client_secret' is required for the 'client_credentials' grant type.\r\nTrace ID: 52b99b1a-fc0c-401c-b2b1-3fac85dfe6cd\r\nCorrelation ID: 95d99f1e-fa0d-48c8-834e-4df2f1a9dd7b\r\nTimestamp: 2016-10-12 13:05:49Z","error_codes":[90014],"timestamp":"2016-10-12 13:05:49Z","trace_id":"52b99b1a-fc0c-401c-b2b1-3fac85dfe6cd","correlation_id":"95d99f1e-fa0d-48c8-834e-4df2f1a9dd7b"}_

These are my test settings, which you can also use if you want:
Auth URL (tried both): 
-	https://login.windows.net/common/oauth2/authorize?resource=https%3A%2F%2Ffacturatiefad-sys.royalfloraholland.com%2F
-	https://login.microsoftonline.com/7e58a9c5-ca4b-4ac7-b347-243188106279/oauth2/authorize?resource=https%3A%2F%2Ffacturatiefad-sys.royalfloraholland.com%2F 
Access token URL (tried both):
-	https://login.microsoftonline.com/common/oauth2/token
-	https://login.microsoftonline.com/7e58a9c5-ca4b-4ac7-b347-243188106279/oauth2/token 
Client ID:
df68d1a3-68e4-4965-816f-b9106a9d565b
Client Secret:
kESmQvsmtwWpacJ1mywse5jW2KIXYqhX0rTL4S7+0vk=

I’ve included pictures of the errors and developer tools.

![error](https://cloud.githubusercontent.com/assets/5955708/19898403/2649a34e-a05c-11e6-987e-c9ec565b3bd7.png)
![errordetails](https://cloud.githubusercontent.com/assets/5955708/19898402/26475b20-a05c-11e6-8312-4d6e3f77f37d.png)

**Comment by czardoz** [comment]
Hi @MonneOnrust, this repository is present to track specific bugs related to a component of the Postman app. I've opened an issue for you at our app related bug tracker: https://github.com/postmanlabs/postman-app-support/issues/2451

It would be great if you could comment on the issue with your app version information :)
