### ISSUE TITLE
How can we use PostmanApi in nodejs/newman

### ISSUE THREAD

**Issue by mike123vn** [postmanlabs/postman-runtime#151]
Can i use  PostmanApi in nodejs/newman to set global variable in newman/nodejs?
Example:
require (postman-runtime);
PostmanApi = new PostmanApi(__masked, __globals); ==>I don't know where i can find masked and globals...
..............................
PostmanApi.setGlobalVariable(token,"AAA")

**Comment by czardoz** [comment]
@mike123vn the Postman API is exposed in the test/pre-request script sandbox. Ideally, there should be no reason for you to make your own instance. 

If you want to run a collection, I recommend using Newman as a library: https://github.com/postmanlabs/newman#newmanrunoptions-object--callback-function--run-eventemitter

You can pass in any custom globals or environment variables there :)
