### ISSUE TITLE
Digest auth request goes into an infinite loop with `interactive:true` flag

### ISSUE THREAD

**Issue by kamalaknn** [postmanlabs/postman-runtime#307]
With `interactive:true` flag enabled,  digest auth request goes into an infinite loop never completing.

Options for run method

```
{ data: {},
  disableSNR: true,
  environment: { values: [] },
  globals: 
   { values: 
      [...] },
  iterationCount: 1,
  stopOnError: true,
  useSystemProxy: true,
  requester: 
   { followRedirects: true,
     strictSSL: false,
     cookieJar: RequestJar { _jar: [Object] } },
  fileResolver: 
   {...},
  authorizer: { interactive: true } }
```

**Comment by kunagpal** [comment]
@kamalaknn An option called `maxReplay` will have to be added to fix this.

**Comment by kamalaknn** [comment]
@kunagpal and `maxReplay` will have a sensible default, right?

**Comment by kunagpal** [comment]
@kamalaknn Yes, the default will be set to `1`.

**Comment by kunagpal** [comment]
This is being fixed in https://github.com/postmanlabs/postman-runtime/pull/336

**Comment by kamalaknn** [comment]
Should be fixed with `ReplayController` now.
