### ISSUE TITLE
variable resolution in history and tests

### ISSUE THREAD

**Issue by Miamoto-Musashi** [postmanlabs/postman-runtime#34]
Hello,
in latest version when i run a call or a test what appear in history panel is the call with environment variables not resolved (not evaluated) even if the call is sucessfull, meaning variables are resolved.

whould be usefull to have the history but specially test runs with actual real calls with variable resolved

Ex.  http://localhost:8080//rest/sales/reports 
instead of 
{{HOST}}:{{PORT}}/rest/sales/reports

**Comment by shamasis** [comment]
Issue migrated to postman-app-support. Closing Here.
