### ISSUE TITLE
GET request not sending defined HEADERS (MAC App)

### ISSUE THREAD

**Issue by hartmut-pq** [postmanlabs/postman-runtime#36]
Hi,

**GET request not sending defined HEADERS (MAC App)**

I've defined custom headers which simply are not being sent along with the GET request.

Using 4.5.1 currently, had the same issues with 4.4.3 though...

**Comment by czardoz** [comment]
@hartmut-pq what is the header you are adding?

**Comment by hartmut-pq** [comment]
Hi @czardoz, thanks for coming back. It's a custom header (auth token)

**Comment by hartmut-pq** [comment]
It's a quite strange behaviour, sometimes if you open a new tab and provide the header before sending the first request it's working. I further noticed when restarting the application and the last open tab is restored (along with the headers) it seems to work as well.
If you send the GET request before adding the header and add it later it's not contained at all...

I've had similar issues with POST requests as well, e.g. when changing the value of a header and sending a new request it simply didn't send the new header value but the old one.

**Comment by shamasis** [comment]
Issue migrated to postman-app-support. Closing Here.
