### ISSUE TITLE
Postman using ~1GB of memory

### ISSUE THREAD

**Issue by gotmikhail** [postmanlabs/postman-runtime#371]
Not sure where exactly to put this, but here's a start.

I noticed that postman recently started getting very slow when making calls, then noticed it was very slow on startup as well.

Checking out Chrome's Task Manager, I saw that Postman is using > 900 MB of Memory

![postman_memleak](https://user-images.githubusercontent.com/356867/30165879-a595136c-93af-11e7-9264-d0d36e24010d.PNG)

It remains stable after startup, approximately, when it's standing idle. In use, I made a server call that reports 264ms in time, content-length 2, but it takes several seconds to run. During that call, the memory jumped by ~20MB.

It's getting to the state of almost being unusable. Selecting anything, menu items, changing collections, etc, all have a delay.

**Comment by kamalaknn** [comment]
@gotmikhail [postman-app-support](https://github.com/postmanlabs/postman-app-support/issues) would be the best place to report issues with the Postman App.

From your description, I can see that you are using our Chrome App. Could you try out our native app and check if it works out for you? The download links are here - https://www.getpostman.com/apps

If you are seeing it on the native apps as well please do report an issue on `postman-app-support` with the version number and OS details and we'll take a look at it.
